# Generated by Django 5.2.13 on 2026-05-05 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingAts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fir', models.TextField(blank=True, null=True)),
                ('code_site', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('date_evenement', models.DateField(blank=True, null=True)),
                ('aeronefs_en_cause', models.TextField(blank=True, null=True)),
                ('trajet', models.TextField(blank=True, null=True)),
                ('zone_occurrence', models.TextField(blank=True, null=True)),
                ('configuration_vol', models.TextField(blank=True, null=True)),
                ('description_evenement', models.TextField(blank=True, null=True)),
                ('type_incident', models.TextField(blank=True, null=True)),
                ('causes', models.TextField(blank=True, null=True)),
                ('heure_detection', models.TimeField(blank=True, null=True)),
                ('heure', models.TextField(blank=True, null=True)),
                ('heure_resolution', models.TimeField(blank=True, null=True)),
                ('duree_incident', models.TimeField(blank=True, null=True)),
                ('criticite', models.TextField(blank=True, null=True)),
                ('compte_incident_atm', models.IntegerField(blank=True, null=True)),
                ('mesures_correctives', models.TextField(blank=True, null=True)),
                ('semaine', models.IntegerField(blank=True, null=True)),
                ('jour', models.IntegerField(blank=True, null=True)),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('pays', models.TextField(blank=True, null=True)),
                ('categorie_causes', models.TextField(blank=True, null=True)),
                ('causes_normalisees', models.TextField(blank=True, null=True)),
                ('categorie_causes_normalisees', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staging_ats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StagingAuto',
            fields=[
                ('id_staging_auto', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(blank=True, max_length=150, null=True)),
                ('code_site', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('date_mise_service', models.DateField(blank=True, null=True)),
                ('vehicules', models.CharField(blank=True, max_length=150, null=True)),
                ('anomalies_constatees', models.TextField(blank=True, null=True)),
                ('maintenances_effectuees', models.TextField(blank=True, null=True)),
                ('structure_de_maintenance', models.TextField(blank=True, null=True)),
                ('solutions_proposees', models.TextField(blank=True, null=True)),
                ('etat_de_fonctionnement', models.CharField(blank=True, max_length=100, null=True)),
                ('etat_disponibilite', models.IntegerField(blank=True, null=True)),
                ('tourelle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('laterale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acceleration_80kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vitesse_max_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tenue_de_route', models.CharField(blank=True, max_length=50, null=True)),
                ('freinage', models.CharField(blank=True, max_length=50, null=True)),
                ('suspection', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('semaine', models.IntegerField(blank=True, null=True)),
                ('categorie_anomalie', models.CharField(blank=True, max_length=100, null=True)),
                ('sous_categorie_anomalie', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_criticite', models.CharField(blank=True, max_length=50, null=True)),
                ('heure_debut_maintenance', models.TimeField(blank=True, null=True)),
                ('heure_fin_maintenance', models.TimeField(blank=True, null=True)),
                ('date_maintenance', models.DateField(blank=True, null=True)),
                ('duree_maintenance', models.TimeField(blank=True, null=True)),
                ('cout_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_maintenance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'STAGING_AUTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StagingGestionApproAchat',
            fields=[
                ('id_staging', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(blank=True, max_length=150, null=True)),
                ('service', models.CharField(blank=True, max_length=150, null=True)),
                ('code_magasin', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_magasin', models.CharField(blank=True, max_length=150, null=True)),
                ('code_article', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle_article', models.TextField(blank=True, null=True)),
                ('categorie_article', models.CharField(blank=True, max_length=150, null=True)),
                ('code_fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_fournisseur', models.CharField(blank=True, max_length=200, null=True)),
                ('pays_fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('type_fournisseur', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse_mail', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('code_type_achat', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle_type_achat', models.CharField(blank=True, max_length=150, null=True)),
                ('description_type_achat', models.TextField(blank=True, null=True)),
                ('categorie_achat', models.CharField(blank=True, max_length=150, null=True)),
                ('quantite_commandee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantite_recue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantite_conforme', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantite_entree', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantite_sortie', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('delai_livraison', models.IntegerField(blank=True, null=True)),
                ('date_operation', models.DateField(blank=True, db_column='DATE_OPERATION', null=True)),
                ('date_commande', models.DateField(blank=True, db_column='DATE_COMMANDE', null=True)),
                ('code_site', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('code_service', models.CharField(blank=True, max_length=50, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'STAGING_GESTION_APPRO_ACHAT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StagingMaintenance',
            fields=[
                ('id_staging_maintenance', models.AutoField(db_column='ID_STAGING_MAINTENANCE', primary_key=True, serialize=False)),
                ('date_maintenance', models.DateField(blank=True, db_column='DATE_MAINTENANCE', null=True)),
                ('jour', models.IntegerField(blank=True, db_column='JOUR', null=True)),
                ('mois', models.IntegerField(blank=True, db_column='MOIS', null=True)),
                ('annee', models.IntegerField(blank=True, db_column='ANNEE', null=True)),
                ('semaine', models.IntegerField(blank=True, db_column='SEMAINE', null=True)),
                ('site', models.CharField(blank=True, db_column='SITE', max_length=100, null=True)),
                ('service', models.CharField(blank=True, db_column='SERVICE', max_length=100, null=True)),
                ('systeme', models.CharField(blank=True, db_column='SYSTEME', max_length=150, null=True)),
                ('type_systeme', models.CharField(blank=True, db_column='TYPE_SYSTEME', max_length=100, null=True)),
                ('type_maintenance', models.CharField(blank=True, db_column='TYPE_MAINTENANCE', max_length=100, null=True)),
                ('intervention', models.CharField(blank=True, db_column='INTERVENTION', max_length=100, null=True)),
                ('programme_maintenance', models.CharField(blank=True, db_column='PROGRAMME_MAINTENANCE', max_length=100, null=True)),
                ('user', models.TextField(blank=True, db_column='USER', null=True)),
                ('action_correctrice', models.TextField(blank=True, db_column='ACTION_CORRECTRICE', null=True)),
                ('heure_reception', models.TimeField(blank=True, db_column='HEURE_RECEPTION', null=True)),
                ('heure_constat', models.TimeField(blank=True, db_column='HEURE_CONSTAT', null=True)),
                ('heure_resolution', models.TimeField(blank=True, db_column='HEURE_RESOLUTION', null=True)),
                ('cout_maintenance', models.DecimalField(blank=True, db_column='COUT_MAINTENANCE', decimal_places=2, max_digits=12, null=True)),
                ('statut_maintenance', models.CharField(blank=True, db_column='STATUT_MAINTENANCE', max_length=50, null=True)),
                ('observation', models.TextField(blank=True, db_column='OBSERVATION', null=True)),
                ('duree_maintenance', models.TimeField(blank=True, db_column='DUREE_MAINTENANCE', null=True)),
                ('delai_prise_en_charge', models.TimeField(blank=True, db_column='DELAI_PRISE_EN_CHARGE', null=True)),
                ('direction', models.CharField(blank=True, db_column='DIRECTION', max_length=100, null=True)),
                ('code_service', models.CharField(blank=True, db_column='CODE_SERVICE', max_length=50, null=True)),
                ('code_systeme', models.CharField(blank=True, db_column='CODE_SYSTEME', max_length=20, null=True)),
                ('code_action_correctrice', models.CharField(blank=True, db_column='CODE_ACTION_CORRECTRICE', max_length=20, null=True)),
            ],
            options={
                'db_table': 'STAGING_MAINTENANCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimAnomalie',
            fields=[
                ('id_type_anomalie', models.AutoField(db_column='ID_TYPE_ANOMALIE', primary_key=True, serialize=False)),
                ('code_anomalie', models.CharField(db_column='CODE_ANOMALIE')),
                ('description_panne', models.TextField(blank=True, db_column='DESCRIPTION_PANNE', null=True)),
                ('categorie_anomalie', models.TextField(blank=True, db_column='CATEGORIE_ANOMALIE', null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_ANOMALIE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimArticle',
            fields=[
                ('id_article', models.AutoField(db_column='ID_ARTICLE', primary_key=True, serialize=False)),
                ('code_article', models.CharField(db_column='CODE_ARTICLE', max_length=10)),
                ('nom_article', models.TextField(db_column='NOM_ARTICLE')),
                ('categorie_article', models.CharField(blank=True, db_column='CATEGORIE_ARTICLE', max_length=100, null=True)),
                ('unite_article', models.CharField(blank=True, db_column='UNITE_ARTICLE', max_length=10, null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_ARTICLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimCauseIncident',
            fields=[
                ('id_cause', models.AutoField(primary_key=True, serialize=False)),
                ('cause', models.TextField(blank=True, db_column='CAUSE', null=True)),
                ('categorie_cause', models.TextField(blank=True, db_column='CATEGORIE_CAUSE', null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_CAUSE_INCIDENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimCriticite',
            fields=[
                ('id_criticite', models.AutoField(db_column='ID_CRITICITE', primary_key=True, serialize=False)),
                ('niveau_criticite', models.TextField(db_column='NIVEAU CRITICITE')),
            ],
            options={
                'db_table': 'TABLE_DIM_CRITICITE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimEtatPerformance',
            fields=[
                ('id_etat_performance', models.IntegerField(db_column='ID_ETAT_PERFORMANCE', primary_key=True, serialize=False)),
                ('tenue_route', models.CharField(blank=True, db_column='TENUE_ROUTE', max_length=50, null=True)),
                ('freinage', models.CharField(blank=True, db_column='FREINAGE', max_length=50, null=True)),
                ('suspension', models.CharField(blank=True, db_column='SUSPENSION', max_length=50, null=True)),
                ('direction', models.CharField(blank=True, db_column='DIRECTION', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_ETAT_PERFORMANCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimFournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(db_column='ID_FOURNISSEUR', primary_key=True, serialize=False)),
                ('code_fournisseur', models.CharField(blank=True, db_column='CODE_FOURNISSEUR', max_length=20, null=True)),
                ('nom_fournisseur', models.TextField(db_column='NOM_FOURNISSEUR')),
                ('pays', models.TextField(blank=True, db_column='PAYS', null=True)),
                ('type_fournisseur', models.TextField(blank=True, db_column='TYPE_FOURNISSEUR', null=True)),
                ('adresse_mail', models.TextField(blank=True, db_column='ADRESSE_MAIL', null=True)),
                ('telephone', models.CharField(blank=True, db_column='TELEPHONE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_FOURNISSEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimIntervention',
            fields=[
                ('id_intervention', models.AutoField(db_column='ID_INTERVENTION', primary_key=True, serialize=False)),
                ('code_intervention', models.CharField(blank=True, db_column='CODE_INTERVENTION', max_length=20, null=True)),
                ('libelle_intervention', models.CharField(blank=True, db_column='LIBELLE_INTERVENTION', max_length=100, null=True)),
                ('action_intervention', models.TextField(blank=True, db_column='ACTION_INTERVENTION', null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_INTERVENTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimMagasin',
            fields=[
                ('id_magasin', models.AutoField(db_column='ID_MAGASIN', primary_key=True, serialize=False)),
                ('code_magasin', models.CharField(db_column='CODE_MAGASIN', max_length=10)),
                ('nom_magasin', models.TextField(blank=True, db_column='NOM_MAGASIN', null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_MAGASIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimMaintenance',
            fields=[
                ('id_type_maintenance', models.AutoField(db_column='ID_TYPE_MAINTENANCE', primary_key=True, serialize=False)),
                ('code_maintenance', models.CharField(db_column='CODE_MAINTENANCE', max_length=5)),
                ('libelle_maintenance', models.TextField(db_column='LIBELLE_MAINTENANCE')),
            ],
            options={
                'db_table': 'TABLE_DIM_MAINTENANCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimService',
            fields=[
                ('id_service', models.AutoField(db_column='ID_SERVICE', primary_key=True, serialize=False)),
                ('nom_service', models.TextField(db_column='NOM_SERVICE')),
                ('direction', models.TextField(db_column='DIRECTION')),
                ('code_service', models.CharField(blank=True, db_column='CODE_SERVICE', max_length=20, null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_SERVICE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimSite',
            fields=[
                ('id_site', models.AutoField(db_column='ID_SITE', primary_key=True, serialize=False)),
                ('code_site', models.CharField(db_column='CODE_SITE', max_length=10)),
                ('nom_site', models.TextField(db_column='NOM_SITE')),
                ('pays', models.TextField(db_column='PAYS')),
                ('region', models.TextField(db_column='REGION')),
            ],
            options={
                'db_table': 'TABLE_DIM_SITE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimSysteme',
            fields=[
                ('id_systeme', models.AutoField(db_column='ID_SYSTEME', primary_key=True, serialize=False)),
                ('code_systeme', models.CharField(db_column='CODE_SYSTEME', max_length=20)),
                ('nom_systeme', models.TextField(db_column='NOM_SYSTEME')),
                ('type_systeme', models.TextField(db_column='TYPE_SYSTEME')),
            ],
            options={
                'db_table': 'TABLE_DIM_SYSTEME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimTemps',
            fields=[
                ('id_temps', models.AutoField(db_column='ID_TEMPS', primary_key=True, serialize=False)),
                ('jour', models.IntegerField(db_column='JOUR')),
                ('mois', models.IntegerField(db_column='MOIS')),
                ('semaine', models.IntegerField(blank=True, db_column='SEMAINE', null=True)),
                ('annee', models.IntegerField(db_column='ANNEE')),
                ('date', models.DateField(db_column='DATE')),
            ],
            options={
                'db_table': 'TABLE_DIM_TEMPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimTypeAchat',
            fields=[
                ('id_type_achat', models.AutoField(db_column='ID_TYPE_ACHAT', primary_key=True, serialize=False)),
                ('code_type_achat', models.CharField(blank=True, db_column='CODE_TYPE_ACHAT', max_length=20, null=True)),
                ('libelle_type_achat', models.TextField(db_column='LIBELLE_TYPE_ACHAT')),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('categorie_achat', models.TextField(blank=True, db_column='CATEGORIE_ACHAT', null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_TYPE_ACHAT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimTypeIncidentSysteme',
            fields=[
                ('id_type_incident', models.AutoField(db_column='ID_TYPE_INCIDENT', primary_key=True, serialize=False)),
                ('libelle_incident', models.TextField(blank=True, db_column='LIBELLE_INCIDENT', null=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('categorie_incident', models.TextField(blank=True, db_column='CATEGORIE_INCIDENT', null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_TYPE_INCIDENT_SYSTEME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDimVehicule',
            fields=[
                ('id_vehicule', models.IntegerField(db_column='ID_VEHICULE', primary_key=True, serialize=False)),
                ('code_vehicule', models.TextField(db_column='CODE_VEHICULE')),
                ('nom_vehicule', models.TextField(db_column='NOM_VEHICULE')),
                ('type_vehicule', models.TextField(blank=True, db_column='TYPE_VEHICULE', null=True)),
            ],
            options={
                'db_table': 'TABLE_DIM_VEHICULE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableFaitAnomalieVehicule',
            fields=[
                ('id_anomalie_vehicule', models.AutoField(db_column='ID_ANOMALIE_VEHICULE', primary_key=True, serialize=False)),
                ('duree_indisponibilite', models.TimeField(db_column='DUREE_INDISPONIBILITE')),
            ],
            options={
                'db_table': 'TABLE_FAIT_ANOMALIE_VEHICULE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableFaitCommande',
            fields=[
                ('id_commande_achat', models.AutoField(db_column='ID_COMMANDE_ACHAT', primary_key=True, serialize=False)),
                ('quantite_commande', models.IntegerField(db_column='QUANTITE_COMMANDE')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('montant_total_commande', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'TABLE_FAIT_COMMANDE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableFaitIncidentAtm',
            fields=[
                ('id_incident_atm', models.AutoField(db_column='ID_INCIDENT_ATM', primary_key=True, serialize=False)),
                ('compte_incident_atm', models.IntegerField(blank=True, db_column='COMPTE_INCIDENT_ATM', null=True)),
                ('heure_detection', models.TimeField(db_column='HEURE_DETECTION')),
                ('heure_resolution', models.TimeField(db_column='HEURE_RESOLUTION')),
                ('duree_incident', models.TimeField(db_column='DUREE_INCIDENT')),
            ],
            options={
                'db_table': 'TABLE_FAIT_INCIDENT_ATM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableFaitIncidentSysteme',
            fields=[
                ('id_incident_systeme', models.AutoField(db_column='ID_INCIDENT_SYSTEME', primary_key=True, serialize=False)),
                ('temps_detection', models.TimeField(db_column='TEMPS_DETECTION')),
                ('teumps_resolution', models.TimeField(db_column='TEUMPS_RESOLUTION')),
                ('compte_incident_systeme', models.DecimalField(blank=True, db_column='COMPTE_INCIDENT_SYSTEME', decimal_places=2, max_digits=10, null=True)),
                ('duree_indisponibilite', models.TimeField(db_column='DUREE_INDISPONIBILITE')),
            ],
            options={
                'db_table': 'TABLE_FAIT_INCIDENT_SYSTEME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableFaitMaintenanceSysteme',
            fields=[
                ('id_fait_maintenance_systeme', models.AutoField(db_column='ID_FAIT_MAINTENANCE_SYSTEME', primary_key=True, serialize=False)),
                ('duree_maintenance', models.TimeField(db_column='DUREE_MAINTENANCE')),
                ('cout_maintenance_systeme', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'TABLE_FAIT_MAINTENANCE_SYSTEME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableFaitMaintenanceVehicule',
            fields=[
                ('id_maintenance_vehicule', models.AutoField(db_column='ID_MAINTENANCE_VEHICULE', primary_key=True, serialize=False)),
                ('duree_maintenance', models.TimeField(db_column='DUREE_MAINTENANCE')),
                ('cout_maintenance', models.IntegerField(blank=True, db_column='COUT_MAINTENANCE', null=True)),
            ],
            options={
                'db_table': 'TABLE_FAIT_MAINTENANCE_VEHICULE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableFaitPerformanceVehicule',
            fields=[
                ('id_performance', models.AutoField(db_column='ID_PERFORMANCE', primary_key=True, serialize=False)),
                ('vitesse_max', models.IntegerField(db_column='VITESSE_MAX')),
                ('laterale', models.IntegerField(blank=True, db_column='LATERALE', null=True)),
                ('tourelle', models.IntegerField(db_column='TOURELLE')),
            ],
            options={
                'db_table': 'TABLE_FAIT_PERFORMANCE_VEHICULE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableFaitReceptionAchat',
            fields=[
                ('id_reception', models.AutoField(db_column='ID_RECEPTION', primary_key=True, serialize=False)),
                ('code_reception', models.CharField(blank=True, db_column='CODE_RECEPTION', max_length=10, null=True)),
                ('quantite_recue', models.IntegerField(db_column='QUANTITE_RECUE')),
                ('quantite_conforme', models.IntegerField(db_column='QUANTITE_CONFORME')),
                ('delai_livraison', models.IntegerField(db_column='DELAI_LIVRAISON')),
            ],
            options={
                'db_table': 'TABLE_FAIT_RECEPTION_ACHAT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableFaitStock',
            fields=[
                ('id_stock', models.AutoField(db_column='ID_STOCK', primary_key=True, serialize=False)),
                ('code_stock', models.CharField(blank=True, db_column='CODE_STOCK', max_length=10, null=True)),
                ('quantite_entree', models.IntegerField(db_column='QUANTITE_ENTREE')),
                ('quantite_sortie', models.IntegerField(db_column='QUANTITE_SORTIE')),
            ],
            options={
                'db_table': 'TABLE_FAIT_STOCK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempProgrammeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systeme', models.TextField(blank=True, db_column='SYSTEME', null=True)),
                ('type_systeme', models.TextField(blank=True, db_column='TYPE_SYSTEME', null=True)),
                ('date_maintenance', models.DateField(blank=True, db_column='DATE_MAINTENANCE', null=True)),
                ('programme_maintenance', models.TextField(blank=True, db_column='PROGRAMME_MAINTENANCE', null=True)),
            ],
            options={
                'db_table': 'TEMP_PROGRAMME_MAINTENANCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('USER2', 'Maintenance Systèmes'), ('USER3', 'ATM'), ('USER4', 'Véhicules')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
