# Generated by Django 5.2.13 on 2026-05-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagingats',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stagingauto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='staginggestionapproachat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stagingmaintenance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimanomalie',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimarticle',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimcauseincident',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimcriticite',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimetatperformance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimfournisseur',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimintervention',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimmagasin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimmaintenance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimservice',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimsite',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimsysteme',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimtemps',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimtypeachat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimtypeincidentsysteme',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tabledimvehicule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablefaitanomalievehicule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablefaitcommande',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablefaitincidentatm',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablefaitincidentsysteme',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablefaitmaintenancesysteme',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablefaitmaintenancevehicule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablefaitperformancevehicule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablefaitreceptionachat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablefaitstock',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tempprogrammemaintenance',
            options={'managed': True},
        ),
    ]
